[pytest]
testpaths = tests
python_files = *test*.py
python_classes = *Test*
python_functions = *test*
markers =
    ui: UI-тесты
    api: API-тесты
    smoke: Smoke тесты
    positive: Позитивные тесты
    negative: Негативные тесты
    diagnostic: тесты для диагностики API
